config/routes.rb
Rails.application.routes.draw do
  resources :jobs
  root 'jobs#index'
  # get 'jobs/index'

  # get 'jobs/new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
class Job < ActiveRecord::Base
  validates :title, presence: true
  validates :company, presence: true
  validates :url, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  	def index
	  	@jobs = Job.page(params[:page]).per(9)
	end

  	def new
  		@job = Job.new
  	end

  	def create
	  	@job = Job.new(params.require(:job).permit(:title, :company, :url))
	  	if @job.save
	    	redirect_to root_path
	  	else
	    	render "new"
	  	end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/index.html.erb
<div id="container">
	<div class="panel panel-primary borderColor">
 		<div class="panel-heading panelHeading">
    		<center>
    			<span class="tagLine">JOBS BOARD APPLICATION</span><br>
    			<%= link_to image_tag("jobLogo.png", alt: "Pinned", size: "160x185")%> <br>	
      			<span class="text">“Opportunities don't often come along. So, when they do, you have to grab them.” <br> – Audrey Hepburn</span>
    		</center>
 		 </div>
	</div>
	<span class="jobText">FEATURED JOBS</span>
	<p class="postJob"><%= link_to "POST A JOB", new_job_path, class: "btn btn-success" %></p>
	<div class="jobDiv">
		<% @jobs.each_with_index do |job, index| %>
  			<div class="panel panel-primary panelHeading2">
  				<span class="pin"><%= link_to image_tag("pin.png", alt: "Pinned", size: "30x35")%></span>
  				<div class="panel-heading panelJobHeading">
  					<h4 class="jobTitle"><b><%= job.title %></b></h4>
  				</div>
  				<div class="panel-body">
  					<table>
  						<tr>
  							<td>
  								<span>Company:</span>
  								<span class="jobCompany"> <%= job.company %></span>
  								<br><br>
  								<span><b><%= link_to "Link to Job", job.url %></b></span>  					
  							</td>	
  						</tr>
					</table>
  				</div>
  			</div>
  		<% end %>
	</div>
	<center>
  		<p><%= paginate @jobs %></p>
	</center>
</div>

app/views/jobs/new.html.erb
<div class="panel panel-primary">
	<div class="panel-heading" id="panelJobHeading">				
  		<h4 id="jobTitle"><b>New Job</b></h4>
  	</div>
  	<div class="panel-body">	
  		<%= simple_form_for @job , html: { class: "form-horizontal"} do |form| %>
	  	<div class="form-group">
	  		<%= form.input :title, label: "Job title" %>
	  	</div>
	  	<div class="form-group">
	  		<%= form.input :company, label: "Your company" %>
	  	</div>
	  	<div class="form-group">
	 		<%= form.input :url, label: "Link to job" %>
	  	</div>
	  	<hr/>
	  	<center>
	  		<%= form.button :submit, label: "Post Job", class: "btn btn-success"%>
	  	</center>
		<% end %>
  	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  	<head>
    	<title>Jobs Board Application</title>
    	<%= favicon_link_tag 'jobLogo.png' %>
      	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  	<%= csrf_meta_tags %>
  	</head>
  	<body>
  		<header class="navbar navbar-fixed-top">
			<div class="container">
				<nav>
					<ul class="nav navbar-nav navbar-right">
						<li><%= link_to "HOME",root_path %></li>
						<li><%= link_to "POST A JOB",new_job_path %></li>
					</ul>
				</nav>
			</div>
		</header>
    <%= yield %>
	<hr>
    <p align="center"> Developed by: Jayvee Lugod </p>
  	</body>
</html>